# Generated by Django 4.0.3 on 2022-04-27 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_status', models.IntegerField(blank=True, null=True)),
                ('bucket', models.IntegerField(blank=True, null=True)),
                ('drafting_week', models.DateField(blank=True, null=True)),
                ('fielder_ecd', models.DateField(blank=True, null=True)),
                ('fielder_sub_date', models.DateField(blank=True, null=True)),
                ('design_sub_date', models.DateField(blank=True, null=True)),
                ('field_correct_sub_date', models.DateField(blank=True, null=True)),
                ('design_correct_sub_date', models.DateField(blank=True, null=True)),
                ('invoicing_status_field', models.IntegerField(blank=True, null=True)),
                ('invoicing_status_design', models.IntegerField(blank=True, null=True)),
                ('invoicing_remark', models.TextField(blank=True, null=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billadded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
