# Generated by Django 4.0.3 on 2022-06-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_bill_bucket_alter_bill_invoicing_status_design_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='fielder_ecd',
        ),
    ]
