# Generated by Django 4.0.3 on 2022-04-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ecd',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task_media',
            name='media',
            field=models.FileField(upload_to='task_media/'),
        ),
    ]
