# Generated by Django 4.0.3 on 2022-04-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_ecd_alter_task_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ecd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
