# Generated by Django 4.0.3 on 2022-05-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_tasks_activity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_media',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activity_tasks'),
        ),
        migrations.AlterField(
            model_name='task_remark',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.activity_tasks'),
        ),
    ]
