# Generated by Django 4.0.3 on 2022-04-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_ecd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ecd',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
