# Generated by Django 4.0.3 on 2022-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_task_media_task_id_alter_task_remark_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_media',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task_remark',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
