# Generated by Django 4.0.3 on 2022-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_task_media_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_media',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task_remark',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
