# Generated by Django 4.0.3 on 2022-04-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activity_ecd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ecd',
            field=models.DateField(blank=True, help_text='Date of ecd', null=True),
        ),
    ]
