# Generated by Django 4.0.3 on 2022-04-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_ecd'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay_users',
            name='emg_relation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bay_users',
            name='emg_number',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
