# Generated by Django 4.0.3 on 2022-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_alter_activity_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='appr_footage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='footage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
