# Generated by Django 4.0.3 on 2022-06-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_alter_activity_appr_footage_alter_activity_footage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cmplt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
