# Generated by Django 4.0.3 on 2022-06-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_activity_cmplt_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pages', models.CharField(max_length=225)),
                ('order_number', models.IntegerField(default=0)),
                ('admin', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('customer_service', models.IntegerField(default=0)),
                ('operations', models.IntegerField(default=0)),
                ('production', models.IntegerField(default=0)),
                ('r_n_d', models.IntegerField(default=0)),
                ('hr', models.IntegerField(default=0)),
                ('account', models.IntegerField(default=0)),
                ('marketing', models.IntegerField(default=0)),
                ('logistics', models.IntegerField(default=0)),
                ('management', models.IntegerField(default=0)),
            ],
        ),
    ]
