# Generated by Django 4.0.3 on 2022-06-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_page_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fielding'), (2, 'Planning'), (3, 'Drafting'), (4, 'QC Job'), (5, 'Research')], primary_key=True, serialize=False),
        ),
    ]
