# Generated by Django 4.0.3 on 2022-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_alter_activities_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='revised_ecd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
