# Generated by Django 4.0.3 on 2022-06-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_fe_users_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_tasks',
            old_name='type',
            new_name='task',
        ),
    ]
