# Generated by Django 4.0.3 on 2022-06-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_rename_type_activity_tasks_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
