# Generated by Django 4.0.3 on 2022-06-17 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_activity_tasks_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('internal_qc_rating', models.IntegerField(blank=True, null=True)),
                ('external_qc_rating', models.IntegerField(blank=True, null=True)),
                ('att_qc_rating', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_detail_activity_id', to='activity.activity')),
                ('doer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_detail_doer', to=settings.AUTH_USER_MODEL)),
                ('qc_eng_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_detail_qc_eng_1', to=settings.AUTH_USER_MODEL)),
                ('qc_eng_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_detail_qc_eng_2', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_detail_status', to='activity.task_status')),
            ],
        ),
    ]
