# Generated by Django 4.0.3 on 2022-06-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_task_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtasks',
            name='status',
        ),
        migrations.AddField(
            model_name='subtasks',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
