# Generated by Django 4.0.3 on 2022-06-29 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_remove_subtasks_status_subtasks_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_detail',
            name='qa_eng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_detail_qa_eng', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_detail',
            name='qa_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task_detail',
            name='qp_eng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_detail_qp_eng', to=settings.AUTH_USER_MODEL),
        ),
    ]
