# Generated by Django 4.0.3 on 2022-07-19 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_task_detail_qa_eng_task_detail_qa_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='assign_fielder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_fielder', to=settings.AUTH_USER_MODEL),
        ),
    ]
