# Generated by Django 4.0.3 on 2022-07-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_alter_activity_assign_fielder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay_users',
            name='superviser_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
