# Generated by Django 4.0.3 on 2022-07-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0026_bay_users_superviser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bay_users',
            name='state',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
