from activity.views.page_permission import *
from activity.views.task_details import *
from activity.views.create_activity import *
from activity.views.activity_list import *
from activity.views.activity_calendar import *
from activity.views.media_list import *
from activity.views.view_activity import *
from activity.views.activities import *
from activity.views.login import *
from activity.views.logout import *
from activity.views.reset_password import *
from activity.views.ajax import *
from activity.views.dashboard import *
from activity.views.fe_users import *
from activity.views.csv_activity_list import *